### ISSUE TITLE
Tests do not pass and drain RAM, after 1.5 hours 55 GR of RAM were eaten

### ISSUE THREAD

**Issue by Altai-man** [JJ/p6-river#16]
Just run `zef install Perl6::Ecosystem` and watch how `01-modules.t` process memory usage grows bigger and bigger.

**Comment by JJ** [comment]
That is mainly due to circular references in modules introduced explicitly for test purpose.

There's no easy way to detect them, other than accept-list or reject-list them. But it is also the reason why I opened this issue
https://github.com/Raku/ecosystem/issues/391, which was rejected. However, it's fair enough. Circular references might show up in other, actual modules. So thanks for the report and I'll try to fix that as soon as possible.

**Comment by Altai-man** [comment]
I might be wrong, but won't the simple "cache everything seen and don't go further, possibly sticking in a filler there" work?

**Comment by JJ** [comment]
> I might be wrong, but won't the simple "cache everything seen and don't go further, possibly sticking in a filler there" work?

That might do to detect circular references. Will give it a try, thanks for the suggestion.

**Comment by Altai-man** [comment]
It is a common pattern for dealing with walking a possibly cyclic graph: when you walk a module name, add it to a set of seen names, if the name was already present - return, else recurse to its deps passing the set along.

**Comment by JJ** [comment]
This didn't work. It actually eliminated *any* distribution it has seen, thus causing #23. I'll probably revert and use rejectlists instead.

**Comment by Altai-man** [comment]
>I'll probably revert and use rejectlists instead.

No, please, just no. Reject list is _not_ a sustainable and safe way to do this. It was not before and will not be in future. Write a better patch using the same technique instead.

**Comment by JJ** [comment]
I'm eliminating self-references on the fly, see further commits on the line.
If references are going to be eliminated, they need to be eliminated for
every dependency chain, there can't be a "global" cache. So you were right
targeting this lines:

https://github.com/angelaig-ugr/efood/commit/439982908335730f551ce8ea501592a6a949699b

But there needs to be a way of checking, _per chain_ if there are repeated
dependencies. Right now there're none, BTW.
